
INSERT INTO uber.trips (name, date, car, client) VALUES ('Arwen Undomiel', '2020-01-01', 'Audi', 'Jane Doe');
INSERT INTO uber.trips (name, date, car, client) VALUES ('Arwen Undomiel', '2020-02-01', 'Audi', 'Bob');
INSERT INTO uber.trips (name, date, car, client) VALUES ('Harry Potter', '2020-01-01', 'Ford', 'John Doe');
INSERT INTO uber.trips (name, date, car, client) VALUES ('Harry Potter', '2020-01-02', 'Ford', 'Alice');

INSERT INTO uber.drivers(name, phone_no, car) VALUES ('Arwen Undomiel', '+34 111111', 'Ford');
INSERT INTO uber.drivers(name, phone_no, car) VALUES ('Harry Potter', '+44 111111', 'Renault');